# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49e962132a295f6868044a753208431e8abcc119bdc84f7a60c24f02bcdc91def93d5b751671d483a466dfa60848cfbcf7ee47dae3be992981d114dab5a645e5

test:
  secret_key_base: 37be7a99854b41db66b1276ce7d03754fd187dfd799148d21215eac609f144270fa4b8b3d067e737bf6212882fc8dce26427cef8a546279bcb9d5df8927b003d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
